name: al_sl_sr
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - numpy==1.23.3
      - pandas
      - scipy
      - scikit-learn==1.0.2
      - matplotlib
      - tqdm
      - xgboost
      - deep-forest==0.1.7